//Action Types

export const SHOW_PRODUCTS = "SHOWPRODUCTS";
export const FETCH_PRODUCTS = "FETCHPRODUCTS";
export const SHOW_SINGLE_PRODUCTS = "FETCHSINGLEPRODUCTS";
export const REMOVE_SINGLE_PRODUCTS = "REMOVESINGLEPRODUCTS";
